---
swagger: "2.0"
info:
  description: "Sleepy is a RESTful querying server for your arbitrary datasets and\
    \ types.\n"
  version: "0.1.0"
  title: "Sleepy"
  contact:
    url: "https://github.com/gkiar/"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: "gkiar.github.io"
basePath: "/sleepy"
tags:
- name: "query"
  description: "Learn about your data"
- name: "file"
  description: "Get pointers to your data"
- name: "schema"
  description: "Get information about your data format"
- name: "upload"
  description: "Add new data"
schemes:
- "https"
- "http"
paths:
  /query:
    get:
      tags:
      - "query"
      summary: "Learn information about data"
      description: "Accepts arbitrary queries compliant with the data schema"
      operationId: "query_data"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "schema"
        in: "query"
        description: "Name of the data schema being used for the query"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Obj"
        400:
          description: "Invalid query"
      x-swagger-router-controller: "sleepy.controllers.query_controller"
  /file:
    get:
      tags:
      - "file"
      summary: "Get file pointers to data"
      description: "Accepts arbitrary queries compliant with the data schema"
      operationId: "get_files"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "schema"
        in: "query"
        description: "Name of the data schema being used for the query"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Obj"
        400:
          description: "Invalid query"
      x-swagger-router-controller: "sleepy.controllers.file_controller"
  /schema:
    get:
      tags:
      - "schema"
      summary: "Get a data schema"
      description: "Accepts name of an installed data schema to return"
      operationId: "get_schema"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "schema"
        in: "query"
        description: "Name of the data schema to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Obj"
        400:
          description: "Invalid schema"
      x-swagger-router-controller: "sleepy.controllers.schema_controller"
  /upload:
    post:
      tags:
      - "upload"
      summary: "uploads an image"
      operationId: "upload_data"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "file to upload"
        required: false
        type: "file"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - sleepy_auth:
        - "read:data"
      deprecated: true
      x-swagger-router-controller: "sleepy.controllers.upload_controller"
securityDefinitions:
  sleepy_auth:
    type: "oauth2"
    authorizationUrl: "http://gkiar.github.io/sleepy/oauth/dialog"
    flow: "implicit"
    scopes:
      read:data: "read contents"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Obj:
    type: "object"
    xml:
      name: "Query"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
    example:
      code: 0
      type: "type"
      message: "message"
